#cloud-config
groups:
  - ubuntu: [root, sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    user_data: |
      #!/bin/bash
      useradd -m -p sa.KT9zrGYeg2 ansible
    ssh_authorized_keys: |
      -  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdX2/gWphW+o2EBdkW3krDSobA91oaAZEj0pXzhuDM4fpX2n9BOBiwLcAOQhYuCIrMQ9ow6Ya
      R/XH0SZ/01/56NktmzS90RlpetF1tfH5+Retp0ndO3+9L55hojGIFsE8fdX6qM7lFWnUiv1VMgw2Ml1IIjV6I/NyaVwWbX38jvZ4Gy5yaPuIAafC1o
      7d6RYVnBJYxdAGz9vvvwJAhppiEGCZZyPrHeG520oTVuiJWeeaAQe3608grkKaRkSW1yM8+ZXkaDaQye0+ghof5y/BqeBoWWm+bxOnap0wg0YSfeja
      3EeNeEMaXzQNQN5FGksF3Ey0CszSczsVCDuo9i5kmKzOj4nBYSS4sAt1cgzmGOAcU9WH7XmHyjST3Kiz2Tjm47L3fErKgNXI/P4Am57kbQq2Y+Ed6R
      YKdfaUKrPO11e/2PY/PTPnXyCbyv5gcg+aQJNTH0DxekyxbfXVIatHgvNXAMbNGgnuwyMcQIV96PVIpd2ojbi+YXHktfBm1EM= 
      rojberr@outlookcom

runcmd:
  - sudo apt-get update
  - sudo apt-get upgrade
