version: '3.3'
services:

  preconfigured-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.preconfigured-jenkins
    container_name: preconfigured-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock